In [2]:
import torch
import numpy as np

## Tensors

- A torch. Tensors is a multi dimensional matrix containing elements of a single data type.

- similar to numpy array but works better on GPU

- default is float32

- suitable for deep learning than a numpy array

## Lists

In [5]:
my_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

## Numpy Arrays

In [7]:
np1 = np.random.rand(3, 4)
np1

array([[0.88386669, 0.5412615 , 0.35811792, 0.37687803],
       [0.37702719, 0.82689658, 0.4921262 , 0.17248632],
       [0.96566932, 0.47080387, 0.55738108, 0.63966974]])

In [10]:
np1.dtype

#defult dtype of numpy is float64

dtype('float64')

## Tensors

In [11]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[-0.3134,  0.8482, -0.4536,  1.4639],
        [-0.1142, -0.0061, -1.4281,  1.3995],
        [ 0.0044, -0.2057,  0.6928, -1.2552]])

In [12]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
# create tensor from numpy array

tensor_from_np = torch.tensor(np1)
tensor_from_np

tensor([[0.8839, 0.5413, 0.3581, 0.3769],
        [0.3770, 0.8269, 0.4921, 0.1725],
        [0.9657, 0.4708, 0.5574, 0.6397]], dtype=torch.float64)

In [16]:
tensor_2d.dtype

torch.float32