## tensor maths operations

- add, subtract, multiply, divide, remainders, exponents
- shorthand, adn longhand
- reassingment

In [1]:
import torch
import numpy as np

In [30]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
#addition

tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
#addition long hand

torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [13]:
# subtraction   
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [14]:
torch.subtract(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [15]:
#multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [8]:
torch.multiply(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [16]:
#division
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [10]:
torch.divide(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [17]:
#remainder
tensor_a % tensor_b

tensor([1, 2, 3, 4])

In [18]:
torch.remainder(tensor_a, tensor_b)

tensor([1, 2, 3, 4])

In [19]:
#exponents / power

torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [20]:
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [22]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [31]:
#reassignment : done using _ symbol (underscore symbol)

tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [32]:
tensor_a

tensor([1, 2, 3, 4])

In [33]:
# tensor_a = tensor_a + tensor_b

tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [34]:
tensor_a

tensor([ 6,  8, 10, 12])