In [3]:
import torch

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Reshape and View

my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
# reshape if we dont know the number of items

my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
#shape will not match hence throw an error

my_torch2 = my_torch2.reshape(2, -1)
my_torch2

RuntimeError: shape '[2, -1]' is invalid for input of size 15

In [11]:
my_torch2 = my_torch2.reshape(3, -1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [4]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
my_torch4 = my_torch3.view(2,5)
my_torch4


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

## Difference between reshape() and view()

https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

https://mr-amit.medium.com/pytorch-view-vs-reshape-a-practical-guide-74bf31eec210


The primary difference between view and reshape in PyTorch is how they handle underlying memory and tensor contiguity.

- view strictly reinterprets the existing memory layout and never copies data, meaning it only works on contiguous tensors.

- reshape acts as a safer, more flexible wrapper; it returns a view if possible, but automatically allocates a new copy of the data if the tensor is non-contiguous.

- A tensor is contiguous when its elements are stored sequentially in a single, uninterrupted block of computer memory.


In [6]:
# with rehsape and view, they will update

my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [10]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [11]:
#slices

my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#grab a specific item
my_torch7[7]

tensor(7)

In [13]:
#grab slice

my_torch8 = my_torch7.reshape(5,2)
my_torch8


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [14]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [16]:
#return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])